# Automatically generated by pb2py
import protobuf as p


class RippleSignedTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 307
    FIELDS = {
        1: ('signature', p.BytesType, 0),
    }

    def __init__(
        self,
        signature: bytes = None
    ) -> None:
        self.signature = signature
