# Automatically generated by pb2py
import protobuf as p
if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None


class RippleSignTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 304
    FIELDS = {
        1: ('protocol_version', p.UVarintType, 0),
        2: ('address_n', p.UVarintType, p.FLAG_REPEATED),
        3: ('account', p.UnicodeType, 0),
        4: ('fee', p.UVarintType, 0),
        5: ('sequence', p.UVarintType, 0),
        6: ('last_ledger_sequence', p.UVarintType, 0),
    }

    def __init__(
        self,
        protocol_version: int = None,
        address_n: List[int] = None,
        account: str = None,
        fee: int = None,
        sequence: int = None,
        last_ledger_sequence: int = None
    ) -> None:
        self.protocol_version = protocol_version
        self.address_n = address_n if address_n is not None else []
        self.account = account
        self.fee = fee
        self.sequence = sequence
        self.last_ledger_sequence = last_ledger_sequence
